TESTBENCH_LIB = libvpicpp-cver.so

CFLAGS += -I$(CVER_VPI_INC_DIR)

RUN_COMMAND=cver +loadvpi=./$(TESTBENCH_LIB):$(INITCALLBACK) $(RTLFILES)

build: lib

.PHONY: clean_sim
cleansim:
	rm -rf verilog.log verilog.dump


