TESTBENCH_LIB = libvpicpp-iverilog.vpi

CFLAGS += -I$(IVERILOG_VPI_INC_DIR)
LDFLAGS += -L$(IVERILOG_VPI_LIB_DIR) -lvpi

SIMBIN = $(TEST)_iverilog.exe

RUN_COMMAND=$(IVERILOG_BIN_DIR)/vvp -m./$(TESTBENCH_LIB:.vpi=) $(SIMBIN)


$(SIMBIN): $(RTLFILES)
	$(IVERILOG_BIN_DIR)/iverilog $^ -s$(TOP) -o$@

sim: $(SIMBIN)

build: lib sim

.PHONY: cleansim
cleansim:
	rm -rf $(SIMBIN) dump.vcd


