TARGET = libvpicpp-vcs.so

ifeq ($(strip $(VCS_HOME)),)
	VCS_HOME=/opt/synopsys/latest
endif

CFLAGS += -I$(VCS_HOME)/include

simbuild: compile
	vcs +vpi +v2k -debug_pp +cli test.v -load $(TARGET):initialCallback 

run: simbuild
	LD_LIBRARY_PATH=$(shell pwd) simv -l simv.log 

.PHONY: clean_sim
clean_sim:
	rm -rf csrc simv* ucli.key

