TARGET = libvpicpp-iverilog.vpi

CFLAGS += -I$(IVERILOG_VPI_INC_DIR)
LDFLAGS += -L$(IVERILOG_VPI_LIB_DIR) -lvpi

compilesim: compile
	$(IVERILOG_BIN_DIR)/iverilog test.v -s$(TOP)

run: compilesim
	$(IVERILOG_BIN_DIR)/vvp -m./$(TARGET:.vpi=) a.out

.PHONY: clean_sim
clean_sim:
	rm -rf a.out


